site_name: Hi~ I'm 赵丹瑞
nav:
  - 个人首页: "index.md"
  - 还没想好: "about.md"
  - '日记':
    - 日记: "日记/math.md"
    - "2024年": 
      - 2024年7月13日: "日记/2024年/2024年7月13日.md"
  - '学习科目':
    - "语文":
      - Chinese: "courses/chinese/c.md"
    - "数学":
      - Math: "courses/math/c.md"
    - "英语":
      - English: "courses/english/c.md"
  - '我的兴趣':
    - 我的兴趣: "个人兴趣/dsa.md"




theme:
  name: material