site_name: Hi~ I'm 赵丹瑞
nav:
  - 个人首页: "index.md"
  - 还没想好: "about.md"
  - '日记':
    - 数学: "数学/math.md"
    - 微积分: "数学/caculus.md"
  - '学习科目':
    - "语文":
      - Chinese: "courses/chinese/c.md"
    - "数学":
      - Math: "courses/math/.md"
  - '我的兴趣':
    - 总述: "数据结构/dsa.md"




theme:
  name: material